---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: demo-app
        image: m1g0r/demo-app:96aff72
        ports:
        - containerPort: 5000
