name: Continuous Integration

on: 
  push:
    paths:
      - 'app/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
 
    steps:
 
     - name: Checkout code
       uses: actions/checkout@v2
 
     - name: Run linter
       run: black ./app
