name: Continuous Integration

on: 
  push:
    paths:
      - 'app/**'

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    env:
       DOCKER_BUILDKIT: "1"
 
    steps:
     - name: Checkout code
       uses: actions/checkout@v2

     - name: Run linter
       run: make lint

     - name: Login to DockerHub
       uses: docker/login-action@v1 
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
 
     - name: Declare SHA vars to use on other actions
       id: vars
       shell: bash
       run: |
         echo "GITHUB_SHA: ${GITHUB_SHA}"
         echo "::set-output name=sha_short::${GITHUB_SHA::7}"  
 
     - name: Run build
       run: make build

     - name: Run push
       run: make push
